apiVersion: apps.nomanoma121.github.io/v1alpha1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: snappy
    app.kubernetes.io/managed-by: kustomize
  name: app-sample
spec:
  source:
    repo: https://github.com/nomanoma121/snappy
    branch: main 
    dockerfilePath: ./Dockerfile
  replicas: 1
  env:
    - name: ENV_VAR
      value: "value"
  envFrom:
    - secretRef:
        name: my-secret
